;draw blurred text
Global Const $hImage_text = _GDIPlus_BitmapCreateFromScan0($iW, $iH / 2)
Global Const $hGfx_text = _GDIPlus_ImageGetGraphicsContext($hImage_text)
Global Const $hPath_text = _GDIPlus_PathCreate()
Global Const $hFamily = _GDIPlus_FontFamilyCreate("Impact")
Global Const $hStringFormat = _GDIPlus_StringFormatCreate()
Global Const $hBrush_txt = _GDIPlus_LineBrushCreate($iW / 2, 0, $iW / 2, $iH / 2, 0xE0FFFFFF, 0xA01A237E) ;_GDIPlus_BrushCreateSolid(0xF02E86FB)
_GDIPlus_LineBrushSetSigmaBlend($hBrush_txt, 0.66, 1)
Global Const $hPen_txt = _GDIPlus_PenCreate(0x801A237E, 1)
_GDIPlus_StringFormatSetAlign($hStringFormat, 1)
_GDIPlus_StringFormatSetLineAlign($hStringFormat, 1)
_GDIPlus_GraphicsSetSmoothingMode($hGfx_text, $GDIP_SMOOTHINGMODE_ANTIALIAS8X8)
_GDIPlus_GraphicsSetTextRenderingHint($hGfx_text, $GDIP_TextRenderingHintAntialias)
_GDIPlus_GraphicsSetPixelOffsetMode($hGfx_text, $GDIP_PIXELOFFSETMODE_HALF)
_GDIPlus_GraphicsSetCompositingQuality($hGfx_text, $GDIP_COMPOSITINGQUALITYHIGHQUALITY)
Global $tLayout = _GDIPlus_RectFCreate()
